FROM maven:3.8.6-openjdk-8 AS build
WORKDIR /app
COPY backend/pom.xml .
COPY backend/src ./src
RUN mvn package -U -DskipTests -B

FROM openjdk:8-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
